return {
  ["sniperkaos"] = 2,
  ["doggyshot123"] = 2,
  ["xayee"] = 2,
  ["legendarysniper203"] = 1,
  ["dynamitebirthday"] = 2,
  ["gavinthelordofdeath"] = 1,
  ["somerandomguy"] = 1,
  ["xebord"] = 1,
  ["jusbestgameralt"] = 1,
  ["doctorfielding"] = 1,
  ["robloxgod8426"] = 1,
  ["imaginalities"] = 1,
  ["yoyoyoyospyro"] = 1,
  ["200ethan"] = 1,
  ["rad1ative"] = 1,
  ["dioritepuff"] = 1,
  ["1"] = 1,
  ["2"] = 2,
  ["3"] = 3,
  ["pee_boy"] = 1,
  ["pee_boy2"] = 2,
  ["pee_boy3"] = 1,
  ["pee_boy4"] = 1,
  ["radiative"] = 1,
  ["Aimb_Ot3"] = 2,
}
